allowedDeprecatedVersions:
  glob: 7.2.3
  inflight: 1.0.6
  source-map: 0.8.0-beta.0
  sourcemap-codec: 1.4.8

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp

overrides:
  '@mdx-js/mdx': 3.1.1
  cookie: '>=0.7.0'
  esbuild: '>=0.25.0'
  vite: 7.1.9
