# allowedDeprecatedVersions:

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp

overrides:
  '@mdx-js/mdx': ^3
  'cookie': '>=0.7.0'
  'esbuild': '>=0.25.0'
  vite: ^7
