/**
 * Represent header names
 */
export const HttpHeaderName = {
  Accept: 'accept',
  ContentType: 'content-type',
  ApiKey: 'x-api-key',
  Authorization: 'authorization',
  Authority: 'authority',
  HMACAuthentication: 'x-hmac-authentication',
  ApiVersion: 'x-api-version',
  PoweredBy: 'x-powered-by',
  Csrf: 'x-csrf-token',
  Xsrf: 'x-xsrf-token',
  XsrfToken: 'xsrf-token',
  XssProtection: 'x-xss-protection',
  XFrameOptions: 'x-frame-options',
  XContentTypeOptions: 'x-content-type-options',
  XForwardedFor: 'x-forwarded-for',
  XForwardedHost: 'x-forwarded-host',
  XForwardedProto: 'x-forwarded-proto',
  AcceptLanguage: 'accept-language',
  ContentLanguage: 'content-language',
  Server: 'server',
  LastModified: 'last-modified',
  UserAgent: 'user-agent',
  XPagination: 'x-pagination',
  RequestId: 'request-id',
  Origin: 'origin',
  Locale: 'locale',
  LogUuid: 'logUuid',
  Nonce: 'X-Nonce',
  CORSError: 'X-CORS-Error',
  XAppRoute: 'x-app-route',
  ReferrerPolicy: 'referrer-policy',
  PermissionsPolicy: 'permissions-policy',
  StrictTransportSecurity: 'strict-transport-security',
} as const;
