#!/bin/bash

# Single script for automatic versioning and changelog updates
# Combines all versioning functionality into one file

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color

# Function to print colored output
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_header() {
    echo -e "${PURPLE}[AUTO-VERSION]${NC} $1"
}

# Function to check if we're in a git repository
check_git_repo() {
    if ! git rev-parse --git-dir > /dev/null 2>&1; then
        print_error "Not in a git repository!"
        exit 1
    fi
}

# Function to get the latest commit hash
get_latest_commit() {
    git rev-parse HEAD
}

# Function to get the latest commit message
get_latest_commit_message() {
    git log -1 --pretty=%B
}

# Function to check if this commit was already processed
is_commit_processed() {
    local commit_hash="$1"
    local processed_file=".git/version-processed"

    if [ -f "$processed_file" ]; then
        grep -q "$commit_hash" "$processed_file"
    else
        return 1
    fi
}

# Function to check if this is a versioning commit
is_versioning_commit() {
    local commit_msg="$1"
    echo "$commit_msg" | grep -q "chore: bump version\|chore: update changelog\|Auto-generated by auto-version"
}

# Function to create a lock file
create_lock() {
    local lock_file=".git/version-lock"
    local pid_file=".git/version-pid"

    if [ -f "$lock_file" ]; then
        local existing_pid=$(cat "$pid_file" 2>/dev/null || echo "")
        if [ -n "$existing_pid" ] && kill -0 "$existing_pid" 2>/dev/null; then
            print_warning "Another versioning process is running (PID: $existing_pid), skipping..."
            return 1
        else
            # Remove stale lock
            rm -f "$lock_file" "$pid_file"
        fi
    fi

    echo "locked" > "$lock_file"
    echo $$ > "$pid_file"
    return 0
}

# Function to remove lock file
remove_lock() {
    rm -f ".git/version-lock" ".git/version-pid"
}

# Function to mark commit as processed
mark_commit_processed() {
    local commit_hash="$1"
    local processed_file=".git/version-processed"
    echo "$commit_hash" >> "$processed_file"
}

# Function to check if version should be updated
should_update_version() {
    local commit_msg="$1"
    echo "$commit_msg" | grep -qE "^(feat|fix|chore|docs|style|refactor|perf|test)(\(.+\))?:"
}

# Function to check if changelog should be updated
should_update_changelog() {
    local commit_msg="$1"
    echo "$commit_msg" | grep -qE "^(feat|fix|chore|docs|style|refactor|perf|test)(\(.+\))?:"
}

# Function to get commit type
get_commit_type() {
    local commit_msg="$1"
    if echo "$commit_msg" | grep -q "^feat"; then
        echo "feat"
    elif echo "$commit_msg" | grep -q "^fix"; then
        echo "fix"
    elif echo "$commit_msg" | grep -q "^chore"; then
        echo "chore"
    elif echo "$commit_msg" | grep -q "^docs"; then
        echo "docs"
    elif echo "$commit_msg" | grep -q "^style"; then
        echo "style"
    elif echo "$commit_msg" | grep -q "^refactor"; then
        echo "refactor"
    elif echo "$commit_msg" | grep -q "^perf"; then
        echo "perf"
    elif echo "$commit_msg" | grep -q "^test"; then
        echo "test"
    else
        echo "chore"
    fi
}

# Function to update version in package.json
update_version() {
    local commit_msg="$1"
    local package_file="package.json"

    if [ ! -f "$package_file" ]; then
        print_error "package.json not found!"
        return 1
    fi

    # Get current version
    local current_version=$(grep '"version"' "$package_file" | sed 's/.*"version": *"\([^"]*\)".*/\1/')
    print_info "Current version: $current_version"

    # Parse version
    local major=$(echo "$current_version" | cut -d. -f1)
    local minor=$(echo "$current_version" | cut -d. -f2)
    local patch=$(echo "$current_version" | cut -d. -f3)

    # Determine version bump
    local new_version=""
    if echo "$commit_msg" | grep -q "^feat"; then
        # Minor version bump
        minor=$((minor + 1))
        patch=0
        new_version="$major.$minor.$patch"
    elif echo "$commit_msg" | grep -q "^fix\|^chore\|^docs\|^style\|^refactor\|^perf\|^test"; then
        # Patch version bump
        patch=$((patch + 1))
        new_version="$major.$minor.$patch"
    elif echo "$commit_msg" | grep -q "breaking\|major"; then
        # Major version bump
        major=$((major + 1))
        minor=0
        patch=0
        new_version="$major.$minor.$patch"
    else
        # Default patch version bump
        patch=$((patch + 1))
        new_version="$major.$minor.$patch"
    fi

    # Check minor patch max (100)
    if [ "$patch" -gt 100 ]; then
        minor=$((minor + 1))
        patch=0
        new_version="$major.$minor.$patch"
    fi

    print_info "New version: $new_version"

    # Update package.json
    sed -i.bak "s/\"version\": \"$current_version\"/\"version\": \"$new_version\"/" "$package_file"
    rm -f "$package_file.bak"

    print_success "Version updated to $new_version"
    echo "$new_version"
}

# Function to get commit info
get_commit_info() {
    local commit_hash="$1"

    if [ -z "$commit_hash" ]; then
        # Get the latest commit
        commit_hash=$(git rev-parse HEAD)
    fi

    # Get commit message
    local commit_msg=$(git log -1 --pretty=%B "$commit_hash" 2>/dev/null || echo "No commit message")

    # Get commit author
    local commit_author=$(git log -1 --pretty=%an "$commit_hash" 2>/dev/null || echo "Unknown")

    # Get commit date
    local commit_date=$(git log -1 --pretty=%ad --date=short "$commit_hash" 2>/dev/null || echo "$(date +%Y-%m-%d)")

    # Get changed files - use staged files if available, otherwise use commit files
    local changed_files=""
    if git diff --cached --quiet 2>/dev/null; then
        # No staged changes, use commit files
        changed_files=$(git diff-tree --no-commit-id --name-only -r "$commit_hash" 2>/dev/null || echo "")
    else
        # Use staged changes
        changed_files=$(git diff --cached --name-only 2>/dev/null || echo "")
    fi

    echo "$commit_hash|$commit_msg|$commit_author|$commit_date|$changed_files"
}

# Function to format changelog entry
format_changelog_entry() {
    local version="$1"
    local date="$2"
    local commit_info="$3"

    IFS='|' read -r commit_hash commit_msg commit_author commit_date changed_files <<< "$commit_info"

    # Get commit type
    local commit_type=$(get_commit_type "$commit_msg")

    # Simple approach - get staged files or latest commit files
    local changed_files_list=""
    if git diff --cached --quiet 2>/dev/null; then
        # No staged changes, use latest commit files
        changed_files_list=$(git diff-tree --no-commit-id --name-only -r HEAD 2>/dev/null || echo "")
    else
        # Use staged changes (this is what we want for pre-commit)
        changed_files_list=$(git diff --cached --name-only 2>/dev/null || echo "")
    fi

    # Build changelog entry
    local changelog_entry="## [$version] - $date\n"
    changelog_entry+="**Author:** $commit_author\n\n"
    changelog_entry+="### $commit_type\n"
    changelog_entry+="$commit_msg\n\n"

    # Add file sections - simple approach, just list all changed files
    if [ -n "$changed_files_list" ] && [ "$changed_files_list" != "" ]; then
        changelog_entry+="### File Changed\n"
        for file in $(echo "$changed_files_list" | tr '\n' ' '); do
            if [ -n "$file" ]; then
                changelog_entry+="- $file\n"
            fi
        done
        changelog_entry+="\n"
    fi

    changelog_entry+="---\n"

    echo -e "$changelog_entry"
}

# Function to update changelog
update_changelog() {
    local commit_hash="$1"
    local changelog_file="CHANGELOG.md"

    if [ ! -f "$changelog_file" ]; then
        print_error "CHANGELOG.md not found!"
        return 1
    fi

    # Get current version
    local current_version=$(grep '"version"' package.json | sed 's/.*"version": *"\([^"]*\)".*/\1/')
    local release_date=$(date +%Y-%m-%d)

    print_info "Current version: $current_version"
    print_info "Release date: $release_date"

    # Get commit info
    local commit_info=$(get_commit_info "$commit_hash")
    print_info "Commit info: $commit_info"

    # Format changelog entry
    local changelog_entry=$(format_changelog_entry "$current_version" "$release_date" "$commit_info")

    # Insert changelog entry after the header section
    print_info "Updating CHANGELOG.md with version $current_version"

    # Find the insertion point (after the header section)
    local insertion_line=$(grep -n "this project adheres to" "$changelog_file" | cut -d: -f1)
    if [ -z "$insertion_line" ]; then
        # Fallback: insert after line 10 if header not found
        insertion_line=10
    else
        insertion_line=$((insertion_line + 1))
    fi

    # Create temporary file with new entry
    echo -e "$changelog_entry" > /tmp/changelog_entry.tmp

    # Split the file at the insertion point
    head -n $insertion_line "$changelog_file" > /tmp/changelog_header.tmp
    tail -n +$((insertion_line + 1)) "$changelog_file" > /tmp/changelog_footer.tmp

    # Combine: header + new entry + footer
    cat /tmp/changelog_header.tmp /tmp/changelog_entry.tmp /tmp/changelog_footer.tmp > "$changelog_file"

    # Clean up temporary files
    rm -f /tmp/changelog_entry.tmp /tmp/changelog_header.tmp /tmp/changelog_footer.tmp

    print_success "CHANGELOG.md updated successfully with version $current_version"
}

# Function to commit the updated files
commit_updates() {
    local version="$1"

    # Check if there are changes to commit
    if git diff --quiet && git diff --cached --quiet; then
        print_info "No changes to commit"
        return 0
    fi

    print_info "Committing version and changelog updates..."

    # Add the updated files
    git add package.json CHANGELOG.md

    # Commit the changes
    cat > .git/commit-msg.tmp << EOF
chore: bump version and update changelog

- Updated package.json version
- Updated CHANGELOG.md with latest changes
- Auto-generated by auto-version script
EOF

    git commit -F .git/commit-msg.tmp
    rm -f .git/commit-msg.tmp

    print_success "Version and changelog updates committed successfully"
}

# Main function
main() {
    print_header "Starting auto-version process..."

    # Check if we're in a git repository
    check_git_repo

    # Create lock to prevent multiple instances
    if ! create_lock; then
        return 0
    fi

    # Ensure lock is removed on exit
    trap remove_lock EXIT

    # Parse command line arguments
    local pre_commit_mode=false

    while [[ $# -gt 0 ]]; do
        case $1 in
            --pre-commit)
                pre_commit_mode=true
                shift
                ;;
            --help)
                echo "Usage: $0 [OPTIONS]"
                echo ""
                echo "Options:"
                echo "  --pre-commit    Run in pre-commit mode"
                echo "  --help         Show this help message"
                exit 0
                ;;
            *)
                print_error "Unknown option: $1"
                exit 1
                ;;
        esac
    done

    # Get latest commit information
    local commit_hash=$(get_latest_commit)
    local commit_msg=$(get_latest_commit_message)

    # Check if this is a versioning commit (skip to prevent infinite loop)
    if is_versioning_commit "$commit_msg"; then
        print_info "Skipping versioning commit to prevent infinite loop: $commit_msg"
        return 0
    fi

    # Check if this commit was already processed
    if is_commit_processed "$commit_hash"; then
        print_info "Commit $commit_hash already processed, skipping..."
        return 0
    fi

    # Check if this commit has been pushed to origin (skip if already pushed)
    if git show-ref --verify --quiet refs/remotes/origin/$(git branch --show-current); then
        local local_commit=$(git rev-parse HEAD)
        local remote_commit=$(git rev-parse origin/$(git branch --show-current))

        if [ "$local_commit" = "$remote_commit" ]; then
            print_info "Commit already pushed to origin, skipping..."
            return 0
        fi
    fi

    # Determine what to update
    local update_version=false
    local update_changelog=false

    if should_update_version "$commit_msg"; then
        update_version=true
    else
        print_info "Skipping version update based on commit message"
    fi

    if should_update_changelog "$commit_msg"; then
        update_changelog=true
    else
        print_info "Skipping changelog update based on commit message"
    fi

    # Run updates
    local new_version=""

    if [ "$update_version" = true ]; then
        new_version=$(update_version "$commit_msg")
        if [ $? -ne 0 ]; then
            print_error "Version update failed!"
            exit 1
        fi
    fi

    if [ "$update_changelog" = true ]; then
        update_changelog "$commit_hash"
        if [ $? -ne 0 ]; then
            print_error "Changelog update failed!"
            exit 1
        fi
    fi

    # Commit updates if changes were made
    if ([ "$update_version" = true ] || [ "$update_changelog" = true ]); then
        if [ -n "$new_version" ]; then
            commit_updates "$new_version"
        else
            # If only changelog was updated, commit without version
            commit_updates "changelog"
        fi
    fi

    # Mark commit as processed
    mark_commit_processed "$commit_hash"

    print_success "Auto-version process completed successfully!"
}

# Run main function with all arguments
main "$@"
