name: Docker Image CI

on:
  push:
    branches: ['dev', 'main']

jobs:
  call-workflow:
    name: Trigger Docker Image Building and Publishing
    uses: ajrly/gh-workflow-template/.github/workflows/build-docker-image.yml@main
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      image-name: ${{ github.repository }}
      image-tag: ${{ github.run_number }}
      environment: production
